Importação das bibliotecas pandas e numpy

In [1]:
import pandas as pd
import numpy as np

Importando a tabela datatran2026


Usamos o encoding latin para o utf8 e o separador ; conforme está no arquivo csv.

In [2]:
tabela = pd.read_csv('datatran2026.csv', encoding='latin1', sep=';' )
display(tabela.head())
display(tabela.tail())

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,742921,2026-01-01,quinta-feira,04:04:00,TO,153,155,ARAGUAINA,Objeto estático sobre o leito carroçável,Tombamento,...,0,1,3,0,5,"-7,291548","-48,286252",SPRF-TO,DEL02-TO,UOP01-DEL02-TO
1,742942,2026-01-01,quinta-feira,06:40:00,MG,262,"146,1",RIO CASCA,Condutor Dormindo,Colisão frontal,...,4,1,1,4,3,"-20,0240733","-42,7422291",SPRF-MG,DEL03-MG,UOP03-DEL03-MG
2,742943,2026-01-01,quinta-feira,06:58:00,SC,101,193,BIGUACU,Reação tardia ou ineficiente do condutor,Colisão lateral mesmo sentido,...,0,1,2,1,4,"-27,48935222","-48,65565777",SPRF-SC,DEL01-SC,UOP01-DEL01-SC
3,742947,2026-01-01,quinta-feira,07:05:00,DF,60,23,BRASILIA,Reação tardia ou ineficiente do condutor,Colisão traseira,...,0,1,1,1,3,"-15,988927","-48,2263",SPRF-DF,DEL03-DF,UOP01-DEL03-DF
4,742960,2026-01-01,quinta-feira,06:17:00,MT,163,1044,MATUPA,Transitar na contramão,Colisão frontal,...,1,1,3,1,5,"-10,14330603","-54,93075559",SPRF-MT,DEL06-MT,UOP03-DEL06-MT

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
42317,795413,2026-05-30,sábado,23:30:00,MG,365,623,UBERLANDIA,Ingestão de álcool pelo condutor,Colisão traseira,...,0,1,0,0,2,"-18,90771269","-48,29991531",SPRF-MG,DEL15-MG,UOP01-DEL15-MG
42318,795594,2026-07-28,terça-feira,12:30:00,DF,60,"0,3",BRASILIA,Reação tardia ou ineficiente do condutor,Saída de leito carroçável,...,2,1,0,2,2,"-15,883242","-48,063643",SPRF-DF,DEL03-DF,UOP01-DEL03-DF
42319,795706,2026-07-09,quinta-feira,18:45:00,PA,163,312,NOVO PROGRESSO,Acessar a via sem observar a presença dos outr...,Colisão transversal,...,0,0,3,0,2,"-7,028179","-55,419506",SPRF-PA,DEL05-PA,UOP03-DEL05-PA
42320,795871,2026-07-13,segunda-feira,14:06:00,DF,70,6,BRASILIA,Acessar a via sem observar a presença dos outr...,Colisão traseira,...,0,1,0,1,2,"-15,79007522","-48,10886264",SPRF-DF,DEL03-DF,UOP02-DEL03-DF
42321,795942,2026-05-24,domingo,03:00:00,GO,153,"437,2",ANAPOLIS,Reação tardia ou ineficiente do condutor,Colisão com objeto,...,0,0,0,2,1,"-16,30447887","-48,9243713",SPRF-GO,DEL02-GO,UOP01-DEL02-GO

Abaixo as primeiras análises e conferencias na tabela

 quantas linhas e colunas tem?
 
  Quais os tipos de cada coluna?
  
   Quanta memória ocupa? 
   
   Há valores faltantes?

In [3]:
print("shape:", tabela.shape)
print()
tabela.info()
print()
print(tabela.isna().sum())

shape: (42322, 30)

<class 'pandas.DataFrame'>
RangeIndex: 42322 entries, 0 to 42321
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      42322 non-null  int64
 1   data_inversa            42322 non-null  str
 2   dia_semana              42322 non-null  str
 3   horario                 42322 non-null  str
 4   uf                      42322 non-null  str
 5   br                      42322 non-null  int64
 6   km                      42322 non-null  str
 7   municipio               42322 non-null  str
 8   causa_acidente          42322 non-null  str
 9   tipo_acidente           42322 non-null  str
 10  classificacao_acidente  42321 non-null  str
 11  fase_dia                42322 non-null  str
 12  sentido_via             42322 non-null  str
 13  condicao_metereologica  42322 non-null  str
 14  tipo_pista              42322 non-null  str
 15  tracado_via             42322 non-null  str
 16  uso_solo                42322 non-null  str
 17  pessoas                 42322 non-null  int64
 18  mortos                  42322 non-null  int64
 19  feridos_leves           42322 non-null  int64
 20  feridos_graves          42322 non-null  int64
 21  ilesos                  42322 non-null  int64
 22  ignorados               42322 non-null  int64
 23  feridos                 42322 non-null  int64
 24  veiculos                42322 non-null  int64
 25  latitude                42322 non-null  str
 26  longitude               42322 non-null  str
 27  regional                42321 non-null  str
 28  delegacia               42312 non-null  str
 29  uop                     42300 non-null  str
dtypes: int64(10), str(20)
memory usage: 9.7 MB

id                         0
data_inversa               0
dia_semana                 0
horario                    0
uf                         0
br                         0
km                         0
municipio                  0
causa_acidente             0
tipo_acidente              0
classificacao_acidente     1
fase_dia                   0
sentido_via                0
condicao_metereologica     0
tipo_pista                 0
tracado_via                0
uso_solo                   0
pessoas                    0
mortos                     0
feridos_leves              0
feridos_graves             0
ilesos                     0
ignorados                  0
feridos                    0
veiculos                   0
latitude                   0
longitude                  0
regional                   1
delegacia                 10
uop                       22
dtype: int64

In [4]:
# Convertendo  colunas para os tipos certos, data e horario
tabela['data_inversa'] = pd.to_datetime(tabela['data_inversa'])

# Removendo  aspas da coluna horario, com elas o sistema não reconhecia o formato de hora.
# detalhe importante, após a conversão da tabela horario para datetime, se executar esse comando novamente
# vai gerar erro, pois o horário não é mais str, portanto rodar esse comando apenas uma vez ou
# ou resetar o kernel para rodar tudo novamente.
tabela['horario'] = tabela['horario'].str.replace('"', '')
tabela['horario'] = pd.to_datetime(tabela['horario'], format='%H:%M:%S', errors='coerce')

In [5]:
# Criando novas colunas fazendo separação de data e horario
tabela['ano'] = tabela['data_inversa'].dt.year
tabela['mes'] = tabela['data_inversa'].dt.month
tabela['dia'] = tabela['data_inversa'].dt.day
tabela['hora'] = tabela['horario'].dt.hour
tabela['minuto'] = tabela['horario'].dt.minute
tabela['nome_mes'] = tabela['data_inversa'].dt.month_name(locale='pt_BR')
tabela['nome_dia'] = tabela['data_inversa'].dt.day_name(locale='pt_BR')

In [6]:
# Imprimindo apenas as alterações para conferir o resultado


print(tabela[['data_inversa','ano','mes','dia', 'nome_mes', 'nome_dia','horario','hora','minuto']].head())

  data_inversa   ano  mes  dia nome_mes      nome_dia             horario  \
0   2026-01-01  2026    1    1  Janeiro  Quinta-feira 1900-01-01 04:04:00
1   2026-01-01  2026    1    1  Janeiro  Quinta-feira 1900-01-01 06:40:00
2   2026-01-01  2026    1    1  Janeiro  Quinta-feira 1900-01-01 06:58:00
3   2026-01-01  2026    1    1  Janeiro  Quinta-feira 1900-01-01 07:05:00
4   2026-01-01  2026    1    1  Janeiro  Quinta-feira 1900-01-01 06:17:00

   hora  minuto
0     4       4
1     6      40
2     6      58
3     7       5
4     6      17

In [7]:
#verificando se não tem nenhum campo horário preenchido com NAT
print(tabela[tabela['horario'].isna()].head())
# verificando se todas as datas foram convertidas corretamente
print(tabela[tabela['data_inversa'].isna()].head())

Empty DataFrame
Columns: [id, data_inversa, dia_semana, horario, uf, br, km, municipio, causa_acidente, tipo_acidente, classificacao_acidente, fase_dia, sentido_via, condicao_metereologica, tipo_pista, tracado_via, uso_solo, pessoas, mortos, feridos_leves, feridos_graves, ilesos, ignorados, feridos, veiculos, latitude, longitude, regional, delegacia, uop, ano, mes, dia, hora, minuto, nome_mes, nome_dia]
Index: []

[0 rows x 37 columns]
Empty DataFrame
Columns: [id, data_inversa, dia_semana, horario, uf, br, km, municipio, causa_acidente, tipo_acidente, classificacao_acidente, fase_dia, sentido_via, condicao_metereologica, tipo_pista, tracado_via, uso_solo, pessoas, mortos, feridos_leves, feridos_graves, ilesos, ignorados, feridos, veiculos, latitude, longitude, regional, delegacia, uop, ano, mes, dia, hora, minuto, nome_mes, nome_dia]
Index: []

[0 rows x 37 columns]

In [8]:
# Conferindo os dias da semana para certificar de não ter valor incorreto
print(tabela['dia_semana'].unique())

<StringArray>
[ 'quinta-feira',   'sexta-feira',        'sábado',       'domingo',
 'segunda-feira',   'terça-feira',  'quarta-feira']
Length: 7, dtype: str

In [9]:
# VErificando se há linhas duplicadas
print(tabela.duplicated().sum())

0